glx: Add GLX_EXT_get_drawable_attributes
KhronosGroup/OpenGL-Registry pull request #425
Opened 2020-08-24 17:35 UTC by nwnk

While writing some other client library bits, I discovered a case where I wanted to differentiate based on the type of the GLXDrawable, but that there's no query for that. It was trivial to add, so I added it. This extension formalizes it. I picked EXT because this seems uncontroversial and easy to support, but I'm happy to change it to MESA or XORG or RHT or whatever if there's no other interest.

2020-09-02 17:25 UTC, kbrenneman commented
This is more of a minor bikeshedding note, but I'd recommend a name like "GLX_EXT_get_drawable_type", since that's the attribute that it adds.

2020-09-12 22:36 UTC, cubanismo requested changes
I think you need to update externsions/registry.py as well, assign yourself an extension number and include it here instead of XXX.  There may be other housekeeping.  I haven't done a GLX extension since the registry was converted to the new format.  Run through the Readme.md and make sure it all still builds and shows up in the generated web pages.  Other than that, the spec content looks good to me.

2020-09-12 22:36 UTC, cubanismo commented on extensions/EXT/GLX_EXT_get_drawable_type.txt
> +    Incomplete
Assuming this is actually complete now, LGTM.

2020-09-15 20:02 UTC, pdaniell-nv commented
This can be merged once the XXX and "Incomplete" status issues are resolved.

2020-09-24 21:00 UTC, nwnk commented
Updated the registry and generated docs. Not sure why this still shows as Changes Requested though.

2020-09-28 23:46 UTC, cubanismo approved these changes

2020-09-28 23:47 UTC, cubanismo commented
LGTM.  Not sure who to assign to merge?  @pdaniell-nv @oddhack?

2020-09-29 03:54 UTC, pdaniell-nv commented
@oddhack, this is approved to merge. Thanks.

2020-09-29 11:37 UTC, oddhack commented
This is missing the changes to glx.xml but I'll just deal with that, since it's so simple.

2020-09-29 11:37 UTC, merged