TEXTURE_2D_ARRAY for EXT_EGL_image_array
KhronosGroup/OpenGL-Registry pull request #497
Opened 2022-02-22 16:54 UTC by stonesthrow

Closes: https://github.com/KhronosGroup/OpenGL-Registry/issues/496

2022-02-23 11:03 UTC, oddhack approved these changes

2022-03-02 16:09 UTC, pdaniell-nv requested changes

2022-03-02 16:09 UTC, pdaniell-nv commented on extensions/EXT/EXT_EGL_image_array.txt
> +    OpenGL ES 2.0 affects the definition of this extension
```suggestion
    OpenGL ES 2.0 is required
    OpenGL ES 3.0 affects the definition of this extension
```

2022-03-02 16:09 UTC, pdaniell-nv commented on extensions/EXT/EXT_EGL_image_array.txt
> +Interactions with OpenGL ES 2.0
```suggestion
Interactions with OpenGL ES 3.0  
```

2022-03-02 16:10 UTC, pdaniell-nv commented
Merge approved once these little issues are resolved.

2022-03-04 18:34 UTC, stonesthrow commented
Thanks Piers, updated, PTAL.

2022-03-07 23:21 UTC, pdaniell-nv approved these changes

2022-03-07 23:21 UTC, pdaniell-nv commented
@oddhack this is approved to merge.

2022-03-08 04:58 UTC, merged